### ISSUE TITLE
Any way to make use of Options in tera?

### ISSUE THREAD

**Issue by LaylConway** [Keats/tera#276] opened 2018-04-01 13:19 UTC
In my shared layout I've got a login section that should change to show when a user's logged in. I've attempted to implement it this way:

```html
{% if login is undefined %}
    <a href="/user/register" class="item">Register</a>
    <a href="/user/login" class="item">Login</a>
{% else %}
    <a href="#" class="item">Your Account</a>
{% endif %}
```
With the following generic context used by all pages.
```rust
#[derive(Serialize)]
pub struct PageContext<T> {
    pub login: Option<Login>,
    pub model: T,
}
```

However, this doesn't work. It will always see `login` as being defined. Is there any way to make this approach work? If not what would be an alternative or better approach that would work?

**Comment by Keats** [comment] 2018-04-01 13:31
Login is defined in that example, even if it's none. Try with just `if
login`, it should evaluate to a falsy value

**Comment by LaylConway** [comment] 2018-04-01 13:34
I have tried that as well (and flipping around the blocks so it shows the correct block if it works), but it gives the same result. `login` always evaluates to true regardless of what's in it.

**Comment by LaylConway** [comment] 2018-04-01 13:36
Oh I just discovered there's a different bug in my code causing this, my bad

**Comment by LaylConway** [comment] 2018-04-01 13:38
Sorry for the rapid responding and closing and opening.
The other problem I was running into was just that my login would be reset whenever rocket reloaded, which would cause the private cookie key to be regenerated. I've now done a test while logged in correctly and `login` still seems to evalulate to false even with a value set.

**Comment by LaylConway** [comment] 2018-04-01 19:45
I've tracked down the cause of this I think. It only seems to happen if the type stored in the Option has no fields. Adding one single boolean field fixed it.

**Comment by Keats** [comment] 2018-04-02 09:28
Can you add a test to Tera for that so I can have a look?

**Comment by HeroicKatora** [comment] 2018-05-05 16:55
```
#[macro_use]
extern crate serde_derive;
extern crate serde_json;

use serde_json::value::to_value;

#[derive(Serialize)]
struct Empty;

fn main() {
    let value = Some(Empty);
    let value = to_value(&value).unwrap();

    assert_eq!(value, Value::Null);
    eprintln!("{}", value);
}
```

This code prints:
`null`

**Comment by Keats** [comment] 2018-09-02 19:15
Closing if the issue comes from in `serde_json`

**Closed by Keats** 2018-09-02 19:15 UTC

**Comment by HeroicKatora** [comment] 2018-09-02 21:11
Slightly redundant but might be useful for anyone stumbling upon this issue by search. I also discovered another workaround @LaylConway :

The cause is that serde serializes `Some(Struct)` to `null`, where `Struct` is an empty struct.

As a workaround, you can either add any field to the struct or turn it into an empty struct tuple. The former turns it into a proper object while the latter produces `Array([])`.

```good
#[derive(Serialize)]
struct Struct();

#[derive(Serialize)]
struct Struct {
  empty: ()
}
```

**Comment by SirWindfield** [comment] 2020-07-19 08:32
i hate necro-ing issues but I do disagree with the reason this got closed.

I do not think that this should be closed just because it "happens to be" coming from `serde_json`. Yes, parsing an empty struct results in `serde_json` returning `null`. But that doesn't mean that `tera` shouldn't check for it for example. IMO `Value::Null` is falsy as well and should therefore evaluate on it.
